botched/botched/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from user import views as user_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mage/', include('mage.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^home/$', user_views.index, name='home'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

botched/mage/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #/mage/chronicle
    url(r'^chronicle/$', views.ChronicleListView.as_view(), name="chronicle-list"),

    #mage/chronicle/pk
    url(r'^chronicle/(?P<pk>(\d)+)', views.ChronicleWelcomeView.as_view(), name='chronicle-welcome'),

    #mage/chronicle/add-new
    url(r'^chronicle/add-new', views.ChronicleCreteView.as_view(), name='chronicle-create-view'),

############################################### CHARACTERS
    #mage/chronicle/characters/pk
    url(r'^chronicle/characters/(?P<pk>(\d)+)$', views.BaseListView.as_view(), name="base-list"),

    #mage/characters/pk
    url(r'^characters/(?P<pk>(\d)+)', views.BaseDetailView.as_view(), name="base-detail-view"),

    #/mage/characters/add-character
    url(r'^characters/add-character', views.BaseCreateView.as_view(), name="base-create-view"),

    #/mage/characters/delete-character/pk
    url(r'^characters/delete-character/(?P<pk>(\d)+)', views.BaseDeleteView.as_view(), name="base-delete-view"),

    #/mage/characters/edit-character/pk
    url(r'^characters/edit-character/(?P<pk>(\d)+)', views.BaseUpdateView.as_view(), name="base-update-view"),

############################################### ATTRIBUTES
    #/mage/characters/attributes/add-attribute
    url(r'^characters/attributes/add-attribute', views.AttributesCreateView.as_view(),
        name="attributes-create-view"),

    #/mage/characters/attributes/delete-attribute/pk
    url(r'^characters/attributes/delete-attribute/(?P<pk>(\d)+)', views.AttributesDeleteView.as_view(),
        name="attributes-delete-view"),

    #/mage/characters/attributes/edit-attribute/pk
    url(r'^characters/attributes/edit-attribute/(?P<pk>(\d)+)', views.AttributesUpdateView.as_view(),
        name="attributes-update-view"),

############################################### ABILITIES
    #/mage/characters/add-character
    url(r'^characters/abilities/add-abilities', views.AbilitiesCreateView.as_view(),
        name="abilities-create-view"),

    #/mage/characters/delete-character/pk
    url(r'^characters/abilities/delete-abilities/(?P<pk>(\d)+)', views.AbilitiesDeleteView.as_view(),
        name="abilities-delete-view"),

    #/mage/characters/edit-character/pk
    url(r'^characters/abilities/edit-abilities/(?P<pk>(\d)+)', views.AbilitiesUpdateView.as_view(),
        name="abilities-update-view"),

############################################### SPHERES
    #/mage/characters/add-sphere
    url(r'^characters/add-sphere', views.SpheresCreateView.as_view(), name="spheres-create-view"),

    #/mage/characters/delete-character/pk
    url(r'^characters/edit-sphere/(?P<pk>(\d)+)', views.SpheresUpdateView.as_view(), name="spheres-update-view"),

    #/mage/characters/edit-character/pk
    url(r'^characters/delete-sphere/(?P<pk>(\d)+)', views.SpheresDeleteView.as_view(), name="spheres-delete-view"),

############################################### TECHNOCRACY SPHERES
    #/mage/characters/add-techsphere
    url(r'^characters/add-techsphere', views.TechnocracySpheresCreateView.as_view(), name="techsphere-create-view"),

    #/mage/characters/delete-character/pk
    url(r'^characters/delete-techsphere/(?P<pk>(\d)+)', views.TechnocracySpheresUpdateView.as_view(), name="techsphere-delete-view"),

    #/mage/characters/edit-character/pk
    url(r'^characters/edit-techsphere/(?P<pk>(\d)+)', views.TechnocracySpheresDeleteView.as_view(), name="techsphere-update-view"),

############################################### STUFF
    #/mage/characters/find-npc
    url(r'^characters/find-npc', views.NpcSearchView.as_view(), name="find-npc"),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

botched/mage/models.py
from django.db import models
from django.urls import reverse

ESSENCE_CHOICES = [
    (1, "Dynamic"),
    (2, "Static"),
    (3, "Primordial"),
    (4, "Questing"),
    (5, "None")
]


class Chronicle(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('chronicle-list')
        # return reverse('base-list')


class Base(models.Model):
    NATURE_CHOICES = [
        (1, "Activist"),
        (2, "Benefactor"),
        (3, "Contrary"),
        (4, "Crusader"),
        (5, "Hacker"),
        (6, "Idealist"),
        (7, "Innovator"),
        (8, "Kid"),
        (9, "Loner"),
        (11, "Machine"),
        (12, "Mad Scientist"),
        (13, "Martyr"),
        (14, "Monster"),
        (15, "Prophet"),
        (16, "Rogue"),
        (17, "Sensualist"),
        (18, "Survivor"),
        (19, "Traditionalist"),
        (20, "Trickster"),
        (21, "Visionary")
    ]

    player = models.CharField(max_length=200, blank=True, null=True)
    chname = models.ForeignKey('Chronicle', verbose_name="Chronicle name", on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    nature = models.IntegerField(choices=NATURE_CHOICES, blank=True)
    demenor = models.IntegerField(choices=NATURE_CHOICES, blank=True)
    willpower = models.PositiveIntegerField(null=True, blank=True)
    traits = models.TextField(null=True, default="Empty", blank=True)
    backgrounds = models.TextField(null=True, default="Empty", blank=True)
    is_technocrat = models.BooleanField(default=False, blank=True)
    is_mage = models.BooleanField(default=False, blank=True)
    #is_independent_mage = models.BooleanField(default=False, blank=True)
    is_enemy = models.BooleanField(blank=True)
    is_player_character = models.BooleanField(default=False, blank=True)
    picture = models.URLField(max_length=1000, default='http://www.petakids.com/wp-content/uploads/2015/11/Cute-Red-Bunny.jpg')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('base-detail-view', kwargs={'pk': self.id})
        #return reverse('base-list')
    

class Attributes(models.Model):
    name = models.OneToOneField('Base', on_delete=models.CASCADE)
    strength = models.IntegerField(null=True, blank=True, default=1)
    dexterity = models.IntegerField(null=True, blank=True, default=1)
    stamina = models.IntegerField(null=True, blank=True, default=1)
    charisma = models.IntegerField(null=True, blank=True, default=1)
    manipulation = models.IntegerField(null=True, blank=True, default=1)
    apperance = models.IntegerField(null=True, blank=True, verbose_name="appearance", default=1)
    perception = models.IntegerField(null=True, blank=True, default=1)
    intelligencee = models.IntegerField(null=True, blank=True, verbose_name="intelligence", default=1)
    wits = models.IntegerField(null=True, blank=True, default=1)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.name)
    
    def get_absolute_url(self):
        return reverse('base-detail-view', kwargs={'pk': self.name.id})


class Abilities(models.Model):
    name = models.OneToOneField('Base', on_delete=models.CASCADE)
    alertness = models.IntegerField(null=True, blank=True)
    art = models.IntegerField(null=True, blank=True)
    athletics = models.IntegerField(null=True, blank=True)
    awareness = models.IntegerField(null=True, blank=True)
    brawl = models.IntegerField(null=True, blank=True)
    empathy = models.IntegerField(null=True, blank=True)
    expression = models.IntegerField(null=True, blank=True)
    intimidation = models.IntegerField(null=True, blank=True)
    leadership = models.IntegerField(null=True, blank=True)
    streetwise = models.IntegerField(null=True, blank=True)
    subterfuge = models.IntegerField(null=True, blank=True)
    crafts = models.IntegerField(null=True, blank=True)
    secondary_talents = models.CharField(max_length=300, null=True, blank=True)
    drive = models.IntegerField(null=True, blank=True)
    etiquette = models.IntegerField(null=True, blank=True)
    firearms = models.IntegerField(null=True, blank=True)
    martial_arts = models.IntegerField(null=True, blank=True)
    meditation = models.IntegerField(null=True, blank=True)
    melee = models.IntegerField(null=True, blank=True)
    research = models.IntegerField(null=True, blank=True)
    stealth = models.IntegerField(null=True, blank=True)
    survival = models.IntegerField(null=True, blank=True)
    technology = models.IntegerField(null=True, blank=True)
    secondary_skills = models.CharField(max_length=300, null=True, blank=True)
    academics = models.IntegerField(null=True, blank=True)
    computer = models.IntegerField(null=True, blank=True)
    cosmology = models.IntegerField(null=True, blank=True)
    enigmas = models.IntegerField(null=True, blank=True)
    esoterica = models.IntegerField(null=True, blank=True)
    investigation = models.IntegerField(null=True, blank=True)
    law = models.IntegerField(null=True, blank=True)
    medicine = models.IntegerField(null=True, blank=True)
    occult = models.IntegerField(null=True, blank=True)
    politics = models.IntegerField(null=True, blank=True)
    science = models.IntegerField(null=True, blank=True)
    secondary_knowledges = models.CharField(max_length=300, null=True, blank=True)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.name)
    
    def get_absolute_url(self):
        return reverse('base-detail-view', kwargs={'pk': self.name.id})

    
class Spheres(models.Model):
    AFFINITY_SPHERE = [(1, "Correspondence"), (2, "Entropy"), (3, "Forces"), (4, "Life"),
                      (5, "Matter"), (6, "Mind"), (7, "Prime"), (8, "Spirit"), (9, "Time")]
    name = models.OneToOneField('Base', on_delete=models.CASCADE)
    tradition = models.CharField(max_length=200, null=True, blank=True)
    avatar = models.PositiveIntegerField(null=True, blank=True)
    essence = models.IntegerField(choices=ESSENCE_CHOICES, blank=True)
    correspondence = models.IntegerField(null=True, blank=True)
    entropy = models.IntegerField(null=True, blank=True)
    forces = models.IntegerField(null=True, blank=True)
    life = models.IntegerField(null=True, blank=True)
    matter = models.IntegerField(null=True, blank=True)
    mind = models.IntegerField(null=True, blank=True)
    prime = models.IntegerField(null=True, blank=True)
    spirit = models.IntegerField(null=True, blank=True)
    time = models.IntegerField(null=True, blank=True)
    affinity_sphere = models.IntegerField(choices=AFFINITY_SPHERE, null=True, blank=True)
    date_sent = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return "{}".format(self.name)
    
    def get_absolute_url(self):
        return reverse('base-detail-view', kwargs={'pk': self.name.id})

    def get_success_url(self):
        return reverse('base-detail-view', kwargs={'pk': self.name.id})


class TechnocracySpheres(models.Model):
    AFFINITY_SPHERE = [(1, "Data"), (2, "Dimensional Science"), (3, "Entropy"), (4, "Forces"), (5, "Life"),
                       (6, "Matter"), (7, "Mind"), (8, "Primal Utility"), (9, "Time")]
    name = models.OneToOneField('Base', on_delete=models.CASCADE)
    Union = models.CharField(max_length=200, null=True, blank=True)
    avatar = models.PositiveIntegerField(null=True, blank=True)
    essence = models.IntegerField(choices=ESSENCE_CHOICES, blank=True)
    data = models.IntegerField(null=True, blank=True)
    dimensional_science = models.IntegerField(null=True, verbose_name="dimensional science", blank=True)
    entropy = models.IntegerField(null=True, blank=True)
    forces = models.IntegerField(null=True, blank=True)
    life = models.IntegerField(null=True, blank=True)
    matter = models.IntegerField(null=True, blank=True)
    mind = models.IntegerField(null=True, blank=True)
    primal_utility = models.IntegerField(null=True, verbose_name="primal utility", blank=True)
    time = models.IntegerField(null=True, blank=True)
    affinity_sphere = models.IntegerField(choices=AFFINITY_SPHERE, null=True, blank=True)
    date_sent = models.DateTimeField(auto_now_add=True, blank=True)
    
    def __str__(self):
        return "{}".format(self.name)
    
    def get_absolute_url(self):
        return reverse('base-detail-view', kwargs={'pk': self.name.id})

botched/mage/forms.py
from django import forms

class NpcSearchForm(forms.Form):
    name = forms.CharField(max_length=200, help_text="who are you looking for?")

botched/mage/templates/mage/base_detail.html
{% extends 'base.html' %}

{% block section_title %} {{ object.name }} {% endblock %}
{% block content %}

    <p><a href="{% url 'base-update-view' pk=object.pk %}">Edit</a></p>
    <p><strong>Chronicle: {{ object.chname }}</strong></p>

    <div class="col-sm-4">
        <p>Nature: {{ object.get_nature_display }}</p>
        <p>Demenor: {{ object.get_demenor_display }}</p>
        <p>Willpower: {{ object.willpower }}</p>
    </div>
    <div class="col-sm-4">
        <p>Traits: {{ object.traits }}</p>
        <p>Backgrounds: {{object.backgrounds }}</p>
    </div>
    <div class="col-sm-4">
        {% if object.is_mage %}
            <p>Mage: True</p>
        {% else %}
            <p>Mage: False</p>
        {% endif %}
        {% if object.is_technocrat %}
            <p>Technocrat: True</p>
        {% else %}
            <p>Technocrat: False</p>
        {% endif %}

        {% if object.is_player_character %}
            <p><strong>Player: {{ object.player }}</strong></p>
        {% endif %}
    </div>
{% endblock %}

{% block mage %}
    {% if object.is_mage %}
        {% include "mage/base_detail_m.html" %}
    {% endif %}

    {% if object.is_technocrat %}
        {% include "mage/base_detail_t.html" %}
    {% endif %}

{% endblock %}

{% block add_new %}

    <ul class="list-inline banner-social-buttons">
        <li>
        <a href="{% url 'attributes-create-view' %}?mage={{ object.id }}" class="btn btnghost btn-lg">Add Attributes</a>
        </li>
        <li>
        <a href="{% url 'abilities-create-view' %}?mage={{ object.id }}" class="btn btnghost btn-lg">Add Abilities</a>
        </li>
        {% block add_sphere %}
            {% if object.is_mage %}
                {% include "mage/base_detail_add_sphere_link.html" %}
            {% elif object.is_technocrate %}
                {% include "mage/base_detail_add_techsphere_link.html" %}
            {% endif %}
        {% endblock %}
    </ul>

{% endblock %}

botched/mage/templates/mage/base_detail_ab.html
{% extends 'mage/base_detail.html' %}
{% block details %}
<h4><strong>Abilities</strong></h4>
    <div class="row">
        <div class="col-sm-4">
            <ul class="list-group">
                <li class="list-group-item"><strong>Talents</strong></li>
                <li class="list-group-item">Alertness: {{ abili.alertness }}</li>
                <li class="list-group-item">Art: {{ abili.art }}</li>
                <li class="list-group-item">Athletics: {{ abili.athletics }}</li>
                <li class="list-group-item">Awarness: {{ abili.awareness }}</li>
                <li class="list-group-item">Brawl {{ abili.brawl }}</li>
                <li class="list-group-item">Emphaty: {{ abili.empathy }}</li>
                <li class="list-group-item">Expression: {{ abili.expression }}</li>
                <li class="list-group-item">Intimidation: {{ abili.intimidation }}</li>
                <li class="list-group-item">Leadership: {{ abili.leadership }}</li>
                <li class="list-group-item">Streetwise: {{ abili.streetwise }}</li>
                <li class="list-group-item">Subterfuge: {{ abili.subterfuge }}</li>
                <li class="list-group-item">Additional talents: {{ abili.secondary_talents }}</li>
            </ul>
        </div>
         <div class="col-sm-4">
            <ul class="list-group">
                <li class="list-group-item"><strong>Skills</strong></li>
                <li class="list-group-item">Crafts: {{ abili.crafts }}</li>
                <li class="list-group-item">Drive: {{ abili.drive }}</li>
                <li class="list-group-item">Etiquette: {{ abili.etiquette }}</li>
                <li class="list-group-item">Firearms: {{ abili.firearms }}</li>
                <li class="list-group-item">Martial Arts: {{ abili.martial_arts }}</li>
                <li class="list-group-item">Meditation: {{ abili.meditation }}</li>
                <li class="list-group-item">Melee: {{ abili.melee }}</li>
                <li class="list-group-item">Research: {{ abili.research }}</li>
                <li class="list-group-item">Stealth: {{ abili.stealth }}</li>
                <li class="list-group-item">Survival: {{ abili.survival }}</li>
                <li class="list-group-item">Technology: {{ abili.technology }}</li>
                <li class="list-group-item">Additional skills: {{ abili.secondary_skills }}</li>
            </ul>
        </div>
         <div class="col-sm-4">
            <ul class="list-group">
                <li class="list-group-item"><strong>Knowledges</strong></li>
                <li class="list-group-item">Academics: {{ abili.academics }}</li>
                <li class="list-group-item">Computer: {{ abili.computer }}</li>
                <li class="list-group-item">Cosmology: {{ abili.cosmology }}</li>
                <li class="list-group-item">Enigmas: {{ abili.enigmas }}</li>
                <li class="list-group-item">Esoterica: {{ abili.esoterica }}</li>
                <li class="list-group-item">Investigation: {{ abili.investigation }}</li>
                <li class="list-group-item">Law: {{ abili.law }}</li>
                <li class="list-group-item">Medicine: {{ abili.medicine }}</li>
                <li class="list-group-item">Occult: {{ abili.occult }}</li>
                <li class="list-group-item">Politics: {{ abili.politics }}</li>
                <li class="list-group-item">Science: {{ abili.science }}</li>
                <li class="list-group-item">Additional knowledges: {{ abili.secondary_knowledges }}</li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block add_new %}

    <ul class="list-inline banner-social-buttons">
        <li>
        <a href="{% url 'attributes-create-view' %}?mage={{ object.id }}" class="btn btnghost btn-lg">Add Attributes</a>
        </li>
        <li>
        <a href="{% url 'abilities-update-view' pk=abili.id %}?mage={{ object.id }}" class="btn btnghost btn-lg">Edit Abilities</a>
        </li>
        {% block add_sphere %}
            {% if object.is_mage %}
                {% include "mage/base_detail_add_sphere_link.html" %}
            {% elif object.is_technocrate %}
                {% include "mage/base_detail_add_techsphere_link.html" %}
            {% endif %}
        {% endblock %}
    </ul>

{% endblock %}

botched/mage/templates/mage/base_detail_abat.html
{% extends 'mage/base_detail.html' %}
{% block details %}
<h4><strong>Attributes</strong></h4>
    <div class="row">
        <div class="col-sm-4">
            <ul class="list-group">
                <li class="list-group-item"><strong>Physical</strong></li>
                <li class="list-group-item">Strength: {{ attr.strength }}</li>
                <li class="list-group-item">Dexterity: {{ attr.dexterity }}</li>
                <li class="list-group-item">Stamina: {{ attr.stamina }}</li>
            </ul>
        </div>
         <div class="col-sm-4">
            <ul class="list-group">
                <li class="list-group-item"><strong>Social</strong></li>
                <li class="list-group-item">Charisma: {{ attr.charisma }}</li>
                <li class="list-group-item">Manipulation: {{ attr.manipulation }}</li>
                <li class="list-group-item">Apperance: {{ attr.apperance }}</li>
            </ul>
        </div>
         <div class="col-sm-4">
            <ul class="list-group">
                <li class="list-group-item"><strong>Mental</strong></li>
                <li class="list-group-item">Perception: {{ attr.perception }}</li>
                <li class="list-group-item">Intelligence: {{ attr.intelligencee }}</li>
                <li class="list-group-item">Wits: {{ attr.wits }}</li>
            </ul>
        </div>
    </div>

<h4><strong>Abilities</strong></h4>
    <div class="row">
        <div class="col-sm-4">
            <ul class="list-group">
                <li class="list-group-item"><strong>Talents</strong></li>
                <li class="list-group-item">Alertness: {{ abili.alertness }}</li>
                <li class="list-group-item">Art: {{ abili.art }}</li>
                <li class="list-group-item">Athletics: {{ abili.athletics }}</li>
                <li class="list-group-item">Awarness: {{ abili.awareness }}</li>
                <li class="list-group-item">Brawl {{ abili.brawl }}</li>
                <li class="list-group-item">Emphaty: {{ abili.empathy }}</li>
                <li class="list-group-item">Expression: {{ abili.expression }}</li>
                <li class="list-group-item">Intimidation: {{ abili.intimidation }}</li>
                <li class="list-group-item">Leadership: {{ abili.leadership }}</li>
                <li class="list-group-item">Streetwise: {{ abili.streetwise }}</li>
                <li class="list-group-item">Subterfuge: {{ abili.subterfuge }}</li>
                <li class="list-group-item">Additional talents: {{ abili.secondary_talents }}</li>
            </ul>
        </div>
         <div class="col-sm-4">
            <ul class="list-group">
                <li class="list-group-item"><strong>Skills</strong></li>
                <li class="list-group-item">Crafts: {{ abili.crafts }}</li>
                <li class="list-group-item">Drive: {{ abili.drive }}</li>
                <li class="list-group-item">Etiquette: {{ abili.etiquette }}</li>
                <li class="list-group-item">Firearms: {{ abili.firearms }}</li>
                <li class="list-group-item">Martial Arts: {{ abili.martial_arts }}</li>
                <li class="list-group-item">Meditation: {{ abili.meditation }}</li>
                <li class="list-group-item">Melee: {{ abili.melee }}</li>
                <li class="list-group-item">Research: {{ abili.research }}</li>
                <li class="list-group-item">Stealth: {{ abili.stealth }}</li>
                <li class="list-group-item">Survival: {{ abili.survival }}</li>
                <li class="list-group-item">Technology: {{ abili.technology }}</li>
                <li class="list-group-item">Additional skills: {{ abili.secondary_skills }}</li>
            </ul>
        </div>
         <div class="col-sm-4">
            <ul class="list-group">
                <li class="list-group-item"><strong>Knowledges</strong></li>
                <li class="list-group-item">Academics: {{ abili.academics }}</li>
                <li class="list-group-item">Computer: {{ abili.computer }}</li>
                <li class="list-group-item">Cosmology: {{ abili.cosmology }}</li>
                <li class="list-group-item">Enigmas: {{ abili.enigmas }}</li>
                <li class="list-group-item">Esoterica: {{ abili.esoterica }}</li>
                <li class="list-group-item">Investigation: {{ abili.investigation }}</li>
                <li class="list-group-item">Law: {{ abili.law }}</li>
                <li class="list-group-item">Medicine: {{ abili.medicine }}</li>
                <li class="list-group-item">Occult: {{ abili.occult }}</li>
                <li class="list-group-item">Politics: {{ abili.politics }}</li>
                <li class="list-group-item">Science: {{ abili.science }}</li>
                <li class="list-group-item">Additional knowledges: {{ abili.secondary_knowledges }}</li>
            </ul>
        </div>

    </div>

{% endblock %}

{% block add_new %}

    <ul class="list-inline banner-social-buttons">
        <li>
        <a href="{% url 'attributes-update-view' pk=object.attributes.id %}?mage={{ object.id }}" class="btn btnghost btn-lg">Edit Attributes</a>
        </li>
        <li>
        <a href="{% url 'abilities-update-view' pk=abili.id %}?mage={{ object.id }}" class="btn btnghost btn-lg">Edit Abilities</a>
        </li>

        {% block add_sphere %}
            {% if object.is_mage %}
                {% include "mage/base_detail_add_sphere_link.html" %}
            {% elif object.is_technocrat %}
                {% include "mage/base_detail_add_techsphere_link.html" %}
            {% endif %}
        {% endblock %}
    </ul>

{% endblock %}

botched/mage/templates/mage/base_detail_add_sphere_link.html
<li>
    {% if spheres is None %}
        <a href="{% url 'spheres-create-view' %}?mage={{ object.id }}" class="btn btnghost btn-lg">Add Spheres</a>
    {% else %}
        <a href="{% url 'spheres-update-view' pk=spheres.id %}?mage={{ object.id }}" class="btn btnghost btn-lg">Edit Spheres</a>
    {% endif %}
</li

botched/mage/templates/mage/base_detail_add_techsphere_link.html
<li>
    {% if techspheres is None %}
        <a href="{% url 'techsphere-create-view' %}?mage={{ techspheres.id }}" class="btn btnghost btn-lg">Add Spheres</a>
    {% else %}
        <a href="{% url 'techsphere-update-view' pk=techspheres.id %}?mage={{ object.id }}" class="btn btnghost btn-lg">Edit Spheres</a>
    {% endif %}
</li

botched/mage/templates/mage/base_detail_m.html
{% block mage %}
    <h4><strong>Tradition: {{spheres.tradition}}</strong></h4>
    <div class="row">
        <div class="col-sm-4"><p>Avatar: {{ spheres.avatar }}</p></div>
        <div class="col-sm-4"><p>Essence: {{spheres.get_essence_display}}</p></div>
        <div class="col-sm-4"><p>Affinity Sphere: {{spheres.get_affinity_sphere_display}}</p></div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <ul class="list-group">
                <li class="list-group-item">Correspondence: {{ spheres.correspondence }}</li>
                <li class="list-group-item">Entropy: {{ spheres.entropy }}</li>
                <li class="list-group-item">Forces: {{ spheres.forces }}</li>
        </div>
        <div class="col-sm-4">
             <ul class="list-group">
                 <li class="list-group-item">Life: {{ spheres.life }}</li>
                 <li class="list-group-item">Matter: {{ spheres.matter }}</li>
                 <li class="list-group-item">Mind: {{ spheres.mind }}</li>
             </ul>
        </div>
        <div class="col-sm-4">
             <ul class="list-group">
                 <li class="list-group-item">Prime: {{ spheres.prime }}</li>
                 <li class="list-group-item">Spirit: {{ spheres.spirit }}</li>
                 <li class="list-group-item">Time: {{ spheres.time }}</li>
             </ul>
        </div>

        </div>

{% endblock %}

{% block add_sphere %} {% endblock %}

botched/mage/templates/mage/base_list.html
{% extends 'base.html' %}


{% block section_title %}Characters{% endblock %}


{% block content %}
<div class="row">
    {% for base in object_list %}
        <div class="col-md-3">
                <div class="thumbnail">
                    <a href="{% url 'base-detail-view' pk=base.id %}">
                        <img src="{{ base.picture }}"  class="img-rounded" style="max-height: 300px">
                        <div class="caption text-center">
                            <p>{{ base.name }}</p>
                        </div>
                    </a>
                </div>
        </div>
        {% if forloop.counter|divisibleby:"4" and not forloop.last %}
            </div><div class="row">
        {% endif %}
    {% empty %}
        No characters yet.
    {% endfor %}
    </div>

{% endblock %}
{% block add_new %}
    <a href="{% url 'base-create-view' %}" class="btnghost">Add Character</a>
{% endblock %}

botched/mage/templates/mage/chronicle_detail.html
{% extends 'base.html' %}
{% block content %}

<p>Cos</p>

{% endblock %}